# Generated by Django 5.0 on 2024-01-18 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tododb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='Punch',
        ),
        migrations.CreateModel(
            name='Punchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tododb.punch')),
            ],
        ),
    ]
