# Generated by Django 5.0 on 2024-01-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tododb', '0002_rename_todo_punch_punchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchlist',
            name='punch',
        ),
        migrations.AddField(
            model_name='punch',
            name='punchlist_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tododb.punchlist'),
        ),
        migrations.AddField(
            model_name='punchlist',
            name='name_of_punchlist',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
